spring.application.name=trader
server.port=
spring.datasource.url=jdbc:mysql://localhost:3306/cavia_trader_db
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
mybatis.mapper-locations=classpath*:/mapper/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

#spring mail properties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#custom email properties
email.from.address=no-reply@trader.io
email.from.personal=Trader team

#google recaptcha secret key for blocking too many sending email
recaptcha.secret-key=

#custom member properties
member.cash.default=10000000
member.cash.reset=5000000

# JWT properties, DO NOT ADD SECRET KEY
jwt.secret.key=
jwt.access-token.expiration.time=
jwt.refresh-token.expiration.time=

# The default fee rate (%) applied to stock trading unless specified otherwise
stock.default-fee-rate=0.003

# The base rank points each player contributes at the start of a ranked game
score.rank_points_per_player=100
score.rank_reward_rate=2
score.rank_max_score=5000